### ISSUE TITLE
Where is the source code to this APK?

### ISSUE THREAD

**Issue by nonetrix** [PycmShoma/crDroid-QSMod#1]
I don't entirely trust this random APK, what does it do and is the source code available? I am assuming it is the replacement for the quick settings, but also could do anything assuming it has root access 
https://github.com/PycmShoma/crDroid-QSMod/tree/main/system/folder/overlay/QSPanelOverlay

I don't mean to come off as rude just concerned and not trying to assume malice intent

**Comment by PycmShoma** [comment]
Hello.  I provide source code only for popular modules, which I post in various public module repositories for Magisk
